# Generated by Django 2.2.3 on 2020-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank='true', null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank='true', max_length=30, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank='true', max_length=30, null='true'),
            preserve_default='true',
        ),
    ]
