# Generated by Django 2.2.3 on 2020-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200406_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(default='city', max_length=20),
        ),
    ]
