# Generated by Django 2.2.3 on 2020-04-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_cafe_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='name',
            new_name='title',
        ),
    ]
