# Generated by Django 2.2.3 on 2020-04-07 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.Cafe'),
        ),
    ]
