# Generated by Django 2.2.3 on 2020-04-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_feedback_cafe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='content',
            new_name='comment',
        ),
    ]
