# Generated by Django 2.2.3 on 2020-04-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_auto_20200407_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cafe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='rating.Cafe'),
        ),
    ]
